正在监听客户端连接
收到客户端连接+++++++++++++++++++++++++
收到客户端连接+++++++++++++++++++++++++
Traceback (most recent call last):
  File "Listener.py", line 38, in <module>
    main("127.0.0.1", 7999)
  File "Listener.py", line 23, in main
    client_socket, client_address = my_tcp_socket.accept()
  File "/usr/lib/python3.8/socket.py", line 292, in accept
    fd, addr = self._accept()
KeyboardInterrupt
收到客户端事件
开始接收服务器数据
头部是 b'{"event": "login", "account": "fd", "password": "ew", "data_type": "text"}'
开始接收服务器数据
缓冲区已无数据 [Errno 11] Resource temporarily unavailable
body是 b''
接收完成 False
收到登录请求 {'event': 'login', 'account': 'fd', 'password': 'ew', 'data_type': 'text'}
收到客户端事件
开始接收服务器数据
头部是 b'{"event": "login", "account": "12", "password": "34", "data_type": "text"}'
开始接收服务器数据
缓冲区已无数据 [Errno 11] Resource temporarily unavailable
body是 b''
接收完成 False
收到登录请求 {'event': 'login', 'account': '12', 'password': '34', 'data_type': 'text'}
收到客户端事件
开始接收服务器数据
客户端已关闭------------------
body是 b''
头部信息错误
收到客户端事件
开始接收服务器数据
客户端已关闭------------------
body是 b''
头部信息错误
Process Process-1:3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haimeng/HS_tool_server/worker.py", line 91, in get_event
    time.sleep(1)
KeyboardInterrupt
Process Process-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haimeng/HS_tool_server/worker.py", line 91, in get_event
    time.sleep(1)
KeyboardInterrupt
Process Process-1:4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haimeng/HS_tool_server/worker.py", line 91, in get_event
    time.sleep(1)
KeyboardInterrupt
Process Process-1:2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haimeng/HS_tool_server/worker.py", line 91, in get_event
    time.sleep(1)
KeyboardInterrupt
来了新客人++++++++++++++++++++++++++++ 28
事件到来, 转交给worker 0
事件到来, 转交给worker 1
事件到来, 转交给worker 2
客户端已关闭++++++++++++++++++++++++++++++
来了新客人++++++++++++++++++++++++++++ 29
事件到来, 转交给worker 2
事件到来, 转交给worker 3
事件到来, 转交给worker 0
客户端已关闭++++++++++++++++++++++++++++++
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/haimeng/HS_tool_server/manager.py", line 88, in get_client
    sleep(1)
KeyboardInterrupt
